feat[web-20]: add Discover section
weblodz/folio pull request #19
Opened 2024-12-28 14:56 UTC by sofiiavoitkova

2024-12-29 11:27 UTC, MyHKo requested changes

2024-12-29 11:27 UTC, MyHKo commented on src/pages/Home/sections/Discover/components/Content/index.jsx
> +      </Link>
There is no hover effect on this link

2024-12-30 19:20 UTC, GarnaA commented on src/pages/Home/sections/Discover/components/Picture/picture.module.scss
> +    transform 0.6s ease-out;
The cursor should change to a pointer when hovering over the picture

2024-12-31 14:16 UTC, GarnaA approved these changes

2024-12-31 16:19 UTC, AndrZakhara approved these changes

2024-12-31 16:21 UTC, merged